"use client";
import Link from "next/link";
import {PlanStatus,type PlanPresentation} from "./plan-status";
import {useEffect,useState,useRef} from "react";
import {useRouter} from "next/navigation";
import {apiFetch} from "./auth-provider";
import {tasksChanged} from "./task-navigation";

type Item={source_type:string;source_id:string;source_version:number;capability_tag_id:string;focus?:string;reason:string;estimated_hours:number;note:string;title?:string;prerequisites?:string;availability?:string;conditions?:Record<string,string|number>};
type Stage={title:string;items:Item[]};
type Analysis={intent:string;interpretation:string;reusable_basis:string[];priorities:{name:string;reason:string}[];basis_limitations:string[]};
type Payload={analysis?:Analysis;answer?:string;next_steps?:string[];overview:{development_direction?:string;development_goal?:string};stages:Stage[];limitations:string[];resource_gaps:string[]};
type Detail={presentation:PlanPresentation;plan:{id:string;current_version_id:string|null;confirmed_version_id:string|null;status:string;active_run_id:string|null};partner_name:string;request:{development_direction?:string;development_goal?:string;raw_demand?:string};conversation:{submission_id:string;message:string;answer:string}[];payload:Payload|null;hidden:boolean;notice:string|null;versions:{id:string;version_no:number}[];runs:{id:string;run_type:string;status:string;created_at:string;safe_error_message:string|null}[]};
const names:Record<string,string>={course:"课程",lab:"实验",case:"共享案例",unknown:"未知",free:"免费",paid:"付费",pending:"等待处理",running:"正在处理",ready:"已完成",failed:"失败",partial:"部分完成",interrupted:"已中断"};
const display=(v?:string|number)=>names[String(v)]||v||"未知";
async function request<T>(url:string,body?:unknown,method?:string):Promise<T>{const res=await apiFetch(url,{method:method||(body?"POST":"GET"),headers:{"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});if(!res.ok){const data=await res.json().catch(()=>({}));throw new Error(typeof data.detail==="string"?data.detail:"暂时无法完成操作，请刷新后重试");}return res.status===204?undefined as T:res.json();}

export function DevelopmentRequestForm({partnerId,sourceTask=null,sourceCase=null,sourceVersion=null}:{partnerId:string;sourceTask?:string|null;sourceCase?:string|null;sourceVersion?:number|null}){
 const router=useRouter(),[direction,setDirection]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const submission=useRef(crypto.randomUUID());
 async function submit(){setError("");if(!partnerId||!direction.trim()){setError("请选择目标伙伴，并描述想发展的方向。");return;}setBusy(true);try{const result=await request<{plan_id:string}>("/development/plans",{submission_id:submission.current,request:{target_partner_id:partnerId,development_direction:direction,source_task_id:sourceTask,source_case_id:sourceCase,source_case_version:sourceVersion,model_input_allowed:true}});tasksChanged();router.push(`/tasks/${result.plan_id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="card development-form"><h2>发展方向</h2><label className="enablement-field">你希望这个伙伴往什么方向发展？<textarea aria-label="发展方向" rows={5} maxLength={4000} value={direction} onChange={e=>{setDirection(e.target.value);submission.current=crypto.randomUUID();}} placeholder="例如：希望未来能够独立承担企业级 Agent 和 RAG 项目交付。也可以问：这个伙伴下一步适合往哪里发展？"/></label><p className="muted">点击生成，即允许本次分析使用你填写的方向、当前伙伴的最小画像摘要及页面带入的来源上下文。内部附件与案例原文不发送；学习资源仅用于准备，交付能力仍需真实项目验证。</p>{error&&<p role="alert" className="notice-neutral">{error}</p>}<button disabled={busy} onClick={()=>void submit()}>{busy?"正在创建任务…":"生成能力发展建议"}</button></section>;
}
function clean(stages:Stage[]){return stages.map(s=>({title:s.title,items:s.items.map(i=>({source_type:i.source_type,source_id:i.source_id,source_version:i.source_version,capability_tag_id:i.capability_tag_id||"",focus:i.focus||"",reason:i.reason,estimated_hours:i.estimated_hours,note:i.note||""}))}));}
export function DevelopmentPlanDetail({id}:{id:string}){
 const [data,setData]=useState<Detail|null>(null),[error,setError]=useState(""),[selected,setSelected]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[preview,setPreview]=useState(""),[editing,setEditing]=useState<Stage[]|null>(null),[base,setBase]=useState(""),[options,setOptions]=useState<(Item&{capability_tag_ids:string[]})[]>([]);
 const sequence=useRef(0),submission=useRef(crypto.randomUUID());
 async function load(){const seq=++sequence.current;try{const next=await request<Detail>(`/development/plans/${id}${selected?`?version_id=${encodeURIComponent(selected)}`:""}`);if(seq===sequence.current){setData(next);if(next.hidden)setPreview("");}}catch(e){if(seq===sequence.current){setData(null);setPreview("");setError((e as Error).message);}}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),2000);return()=>{clearInterval(timer);sequence.current++;};},[id,selected]);
 useEffect(()=>{setPreview("");},[data?.plan.confirmed_version_id,data?.hidden]);
 useEffect(()=>{if(!preview)return;let live=true;async function refresh(){try{const r=await request<{text:string}>(`/development/plans/${id}/transferable`);if(live)setPreview(r.text);}catch{if(live)setPreview("");}}const t=setInterval(()=>void refresh(),10000);window.addEventListener("focus",refresh);return()=>{live=false;clearInterval(t);window.removeEventListener("focus",refresh);};},[id,!!preview]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn();await load();tasksChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!data)return <div className="page"><p role="status">{error||"正在读取发展建议…"}</p></div>;
 const {plan,payload}=data,analysis=payload?.analysis,running=!!plan.active_run_id,locked=busy||running||plan.status==="archived",historical=!!selected&&selected!==plan.current_version_id;
 const version=(v:string|null)=>v?`V${data.versions.find(x=>x.id===v)?.version_no||"?"}`:"未确认";
 async function chat(){await action(async()=>{await request(`/development/plans/${id}/conversation`,{submission_id:submission.current,based_on_version_id:plan.current_version_id,message});submission.current=crypto.randomUUID();setMessage("");setSelected("");});}
 return <div className="page development-detail"><Link href="/tasks">← 全部任务</Link><div className="page-heading-row"><div><p className="eyebrow">Partner Development</p><h1>{data.partner_name} · 能力发展建议</h1><p>当前版本：<strong>{plan.current_version_id?version(plan.current_version_id)+(plan.current_version_id===plan.confirmed_version_id?"（已确认）":"（草稿）"):"尚未生成"}</strong> · 已确认版本：<strong>{version(plan.confirmed_version_id)}</strong></p><PlanStatus value={data.presentation}/></div></div>
 {error&&<p role="alert" className="notice-neutral">{error}</p>}{running&&<p role="status" className="notice-neutral">正在生成能力发展建议，已有版本仍可查看。</p>}{data.runs[0]?.safe_error_message&&<p className="notice-neutral">{data.runs[0].safe_error_message}</p>}{data.notice&&<p className="notice-neutral">{data.notice}</p>}
 <div className="enablement-actions"><button disabled={locked||!payload||historical} onClick={()=>void action(async()=>{await request(`/development/plans/${id}/confirm`,{version_id:plan.current_version_id});})}>确认当前版本</button><button className="secondary-btn" disabled={locked||!payload||historical} onClick={()=>void action(async()=>{setOptions(await request(`/development/plans/${id}/candidates`));setEditing(clean(payload!.stages));setBase(plan.current_version_id!);})}>结构化编辑</button><button className="secondary-btn" disabled={busy||running} onClick={()=>void action(async()=>{await request(`/agent/tasks/${id}/${plan.status==="archived"?"restore":"archive"}`,{},"PATCH");})}>{plan.status==="archived"?"恢复方案":"归档方案"}</button><button className="secondary-btn" disabled={busy||!plan.confirmed_version_id||data.hidden||plan.status==="archived"} onClick={()=>void action(async()=>{setPreview((await request<{text:string}>(`/development/plans/${id}/transferable`)).text);})}>伙伴可传递视图预览</button></div>
 <section className="card"><h2>发展方向</h2>{!data.hidden&&<p className="development-text">{data.request.raw_demand||data.request.development_direction||data.request.development_goal}</p>}<label className="enablement-field">查看版本<select value={selected} onChange={e=>{setSelected(e.target.value);setEditing(null);}}><option value="">当前版本</option>{data.versions.map(v=><option key={v.id} value={v.id}>V{v.version_no}{v.id===plan.confirmed_version_id?" · 已确认":" · 历史快照"}</option>)}</select></label></section>
 {payload&&<>{analysis&&analysis.intent!=="resources"&&<section className="card" data-testid="analysis"><h2>{analysis.intent==="explore"?"值得考虑的发展方向":"发展方向理解"}</h2><p>{analysis.interpretation}</p>{analysis.reusable_basis.length>0&&<><h3>当前可复用基础</h3>{analysis.reusable_basis.map((s,i)=><p key={i}>{s}</p>)}</>}{analysis.priorities.length>0&&<><h3>建议重点</h3>{analysis.priorities.map((p,i)=><div key={i} className="development-target"><h4>{p.name}</h4><p>{p.reason}</p></div>)}</>}{analysis.basis_limitations.map((s,i)=><p key={i} className="muted">{s}</p>)}</section>}
 {payload.answer&&<section className="card"><p className="development-text">{payload.answer}</p></section>}
 {payload.stages.length>0&&<section className="card" data-testid="stages"><h2>推荐资源</h2>{payload.stages.map((s,index)=><div className="development-target" key={index}><h3>{s.title}</h3>{s.items.map((i,n)=><article className="development-resource" key={n}><h4>{names[i.source_type]} · {i.title}</h4><p>{i.reason}</p><p>先修：{i.prerequisites||"未知"} · 参考投入：{i.estimated_hours} 小时</p><p>费用：{names[String(i.conditions?.cost)]||i.conditions?.cost||"未知"} · 账号：{display(i.conditions?.account_requirement)} · 环境：{display(i.conditions?.environment_requirement)}</p><p>语言：{display(i.conditions?.language)} · 站点：{display(i.conditions?.site)}</p>{i.availability==="available"?<Link href={`/enablement/resources/${i.source_type}/${i.source_id}?source_version=${i.source_version}`}>查看来源与发起跳转</Link>:<p>当前资源不可用，历史引用保留。</p>}</article>)}</div>)}</section>}
 {(payload.limitations.length>0||payload.resource_gaps.length>0)&&<section className="card" data-testid="gaps"><h2>使用提示与资源缺口</h2>{[...payload.limitations,...payload.resource_gaps].map((v,i)=><p key={i}>{v}</p>)}</section>}
 {!!payload.next_steps?.length&&analysis?.intent!=="resources"&&<section className="card"><h2>下一步项目实践</h2>{payload.next_steps.map((s,i)=><p key={i}>{s}</p>)}</section>}
 </>}
 {!data.hidden&&<section className="card" data-testid="conversation"><h2>继续交流</h2><p className="muted">可以询问原因、比较资源，或直接说想怎样调整。解释保留当前版本，实际修改成功后生成新草稿。</p>{data.conversation?.map(m=><div key={m.submission_id} className="development-target"><p><strong>你：</strong>{m.message}</p><p className="development-text"><strong>灵鉴：</strong>{m.answer}</p></div>)}<label className="enablement-field">消息<textarea rows={3} maxLength={2000} value={message} onChange={e=>{setMessage(e.target.value);submission.current=crypto.randomUUID();}} placeholder="为什么推荐这个方向？这两个实验有什么区别？不要基础课，多给实验。"/></label><button disabled={locked||!message.trim()||historical||!plan.current_version_id} onClick={()=>void chat()}>发送</button>{!plan.current_version_id&&!running&&<button className="secondary-btn" disabled={busy||plan.status==="archived"} onClick={()=>void action(async()=>{await request(`/development/plans/${id}/revise`,{submission_id:crypto.randomUUID(),based_on_version_id:null,instruction:"重新生成能力发展建议"});})}>重新生成</button>}</section>}
 {preview&&<section className="card" data-testid="transfer-preview"><h2>伙伴可传递视图</h2><pre className="development-text">{preview}</pre><button disabled={busy} onClick={()=>void action(async()=>{const r=await request<{text:string}>(`/development/plans/${id}/copy`,{version_id:plan.confirmed_version_id});await navigator.clipboard.writeText(r.text);setPreview(r.text);})}>复制内容</button><button className="secondary-btn" onClick={()=>setPreview("")}>关闭预览</button></section>}
 {editing&&<section className="card" data-testid="structured-edit"><h2>结构化编辑</h2>{editing.map((s,si)=><div className="development-target" key={si}><label className="enablement-field">阶段标题<input value={s.title} onChange={e=>setEditing(editing.map((v,j)=>j===si?{...v,title:e.target.value}:v))}/></label><button className="secondary-btn" disabled={si===0} onClick={()=>{const next=[...editing];[next[si-1],next[si]]=[next[si],next[si-1]];setEditing(next);}}>阶段上移</button>{s.items.map((i,ii)=><div key={ii}><p>{options.find(o=>o.source_id===i.source_id)?.title||i.title||"历史资源"}</p><label className="enablement-field">预计投入<input type="number" min="0.5" value={i.estimated_hours} onChange={e=>setEditing(editing.map((v,j)=>j===si?{...v,items:v.items.map((x,k)=>k===ii?{...x,estimated_hours:Number(e.target.value)}:x)}:v))}/></label><button className="secondary-btn" onClick={()=>setEditing(editing.map((v,j)=>j===si?{...v,items:v.items.filter((_,k)=>k!==ii)}:v))}>移除资源</button></div>)}<select aria-label={`阶段 ${si+1} 添加资源`} value="" onChange={e=>{const o=options[Number(e.target.value)];if(!o)return;setEditing(editing.map((v,j)=>j===si?{...v,items:[...v.items,{...o,capability_tag_id:o.capability_tag_ids[0]||"",reason:"用户选择的资源",estimated_hours:1,note:""}]}:v));}}><option value="">添加资源</option>{options.map((o,i)=><option key={i} value={i}>{o.title}</option>)}</select></div>)}<button className="secondary-btn" onClick={()=>setEditing([...editing,{title:"新阶段",items:[]}])}>添加阶段</button><button disabled={busy} onClick={()=>void action(async()=>{await request(`/development/plans/${id}/edit`,{based_on_version_id:base,stages:clean(editing)});setEditing(null);setSelected("");})}>保存新草稿</button><button className="secondary-btn" onClick={()=>setEditing(null)}>取消编辑</button></section>}
 <section className="card"><h2>运行历史</h2>{data.runs.map(r=><p key={r.id}>{r.run_type==="generate"?"生成":"调整"} · {names[r.status]||r.status} · {new Date(r.created_at).toLocaleString("zh-CN")}</p>)}</section></div>;
}
