"use client";
import Link from "next/link";
import {PlanStatus,type PlanPresentation} from "./plan-status";
import {useEffect,useState,useRef} from "react";
import {useRouter} from "next/navigation";
import {apiFetch} from "./auth-provider";
import {tasksChanged} from "./task-navigation";

type Target={capability_tag_id:string;requirement:string;confirmed_gap:boolean;confirmation_note:string};
type Request={target_partner_id:string;request_source:string;raw_demand:string;development_goal:string;trainee_role:string;trainee_count:number|null;known_baseline:string;duration_weeks:number|null;hours_per_week:number|null;constraints:Record<string,string>;accepted_assumptions:Record<string,string>;targets:Target[];source_task_id:string|null;source_case_id:string|null;source_case_version:number|null;model_input_allowed:boolean;partner_goal_allowed:boolean};
type Item={source_type:string;source_id:string;source_version:number;capability_tag_id:string;reason:string;estimated_hours:number;note:string;title?:string;prerequisites?:string;constraint?:{state:string};availability?:string};
type Stage={title:string;items:Item[]};
type Diagnosis={capability_tag_id:string;target_requirement:string;target_satisfaction:string;evidence_status:string;judgment_source:string;problem_type:string;pending_verifications:string[];evidence_refs:Item[];confirmation?:{note:string;source:string}};
type Payload={overview:Request;stages:Stage[];diagnoses:Diagnosis[];limitations:string[];resource_gaps:string[];assumptions:Record<string,string>};
type Detail={presentation:PlanPresentation;plan:{id:string;current_version_id:string|null;confirmed_version_id:string|null;status:string;active_run_id:string|null};partner_name:string;request:Request;payload:Payload|null;hidden:boolean;notice:string|null;versions:{id:string;version_no:number;created_at:string}[];runs:{id:string;run_type:string;status:string;created_at:string;safe_error_message:string|null}[]};
type Candidate=Item&{capability_tag_ids:string[]};
const labels:Record<string,string>={target_partner_id:"目标伙伴",raw_demand:"原始诉求",development_goal:"发展目标",trainee_role:"参训岗位",trainee_count:"参训人数",known_baseline:"人员已知基础",duration_weeks:"周期（周）",hours_per_week:"每周投入（小时）",language:"语言",site:"站点",account:"账号条件",network:"网络条件",environment:"实验环境",cost:"费用要求",budget:"预算",targets:"目标能力与要求",model_input_allowed:"模型发送授权",confirmation_note:"人工确认依据",satisfied:"满足",partially_satisfied:"部分满足",not_satisfied:"不满足（已人工确认）",needs_assessment:"待评估",sufficient:"充分",partial:"部分",missing:"缺失",conflicting:"冲突",model_inference:"模型建议，待业务复核",user_confirmed:"用户明确确认",business_correction:"业务纠正",trainable_gap:"可培养差距",evidence_gap:"证据缺口",non_training_constraint:"非培训限制",needs_clarification:"待澄清",meets:"符合",conflicts:"冲突",unknown:"条件未知，需核实",available:"当前可用",unavailable:"当前不可用，不能跳转",pending:"等待执行",running:"生成中",ready:"生成成功",failed:"生成失败",interrupted:"执行中断",course:"课程",lab:"实验",case:"共享案例"};
const constraints=["language","site","account","network","environment","cost","budget"];
const fresh=():Request=>({target_partner_id:"",request_source:"partner_manager",raw_demand:"",development_goal:"",trainee_role:"",trainee_count:null,known_baseline:"",duration_weeks:null,hours_per_week:null,constraints:{},accepted_assumptions:{},targets:[],source_task_id:null,source_case_id:null,source_case_version:null,model_input_allowed:false,partner_goal_allowed:false});
async function request<T>(url:string,body?:unknown,method="POST"):Promise<T>{const res=await apiFetch(url,body===undefined?{cache:"no-store"}:{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!res.ok){const error=await res.json().catch(()=>({}));throw new Error(typeof error.detail==="string"?error.detail:error.detail?.message||"请求未完成，请检查字段或重新加载。");}return res.status===204?undefined as T:await res.json();}

export function DevelopmentRequestForm({partnerId,sourceTask=null,sourceCase=null,sourceVersion=null,initial,onSave}:{partnerId:string;sourceTask?:string|null;sourceCase?:string|null;sourceVersion?:number|null;initial?:Request;onSave?:(value:Request)=>Promise<void>}){
 const router=useRouter();const [form,setForm]=useState<Request>(initial||fresh);const [tags,setTags]=useState<{id:string;name:string}[]>([]);const [missing,setMissing]=useState<string[]>([]);const [assume,setAssume]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{request<{id:string;name:string}[]>("/development/capabilities").then(setTags).catch(e=>setError(e.message));},[]);
 const value={...form,target_partner_id:partnerId,source_task_id:sourceTask,source_case_id:sourceCase,source_case_version:sourceVersion};
 function set(key:string,v:unknown){setForm(f=>({...f,[key]:v}));}
 async function submit(){setError("");setBusy(true);try{const clarified=await request<{missing_fields:string[]}>("/development/clarify",value);setMissing(clarified.missing_fields);if(clarified.missing_fields.length)return;if(onSave)await onSave(value);else{const result=await request<{plan_id:string}>("/development/plans",{submission_id:crypto.randomUUID(),request:value});tasksChanged();router.push(`/tasks/${result.plan_id}`);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="card development-form"><h2>{initial?"调整后的发展诉求":"发展诉求"}</h2><p className="muted">公司伙伴画像不等于参训人员能力。请填写人员基础；未确认事项可明确接受假设后继续。</p>
 <label className="enablement-field">诉求来源<select value={form.request_source} onChange={e=>set("request_source",e.target.value)}><option value="partner_manager">伙伴发展经理</option><option value="partner">伙伴</option><option value="jointly_confirmed">双方共同确认</option></select></label>
 <div className="development-grid">{["raw_demand","development_goal","trainee_role","known_baseline"].map(key=><label className="enablement-field" key={key}>{labels[key]}<textarea rows={key==="raw_demand"?3:2} maxLength={key==="raw_demand"?4000:2000} value={String(form[key as keyof Request]||"")} onChange={e=>set(key,e.target.value)}/></label>)}
 {["trainee_count","duration_weeks","hours_per_week"].map(key=><label className="enablement-field" key={key}>{labels[key]}<input type="number" min="0.5" max={key==="trainee_count"?100000:key==="duration_weeks"?104:80} step={key==="hours_per_week"?0.5:1} value={String(form[key as keyof Request]??"")} onChange={e=>set(key,e.target.value?Number(e.target.value):null)}/></label>)}</div>
 <h3>目标能力与本次目标要求</h3><select aria-label="添加目标能力" value="" onChange={e=>{if(e.target.value&&!form.targets.some(t=>t.capability_tag_id===e.target.value))set("targets",[...form.targets,{capability_tag_id:e.target.value,requirement:"",confirmed_gap:false,confirmation_note:""}]);}}><option value="">选择正式能力标签</option>{tags.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>
 {form.targets.map((t,i)=><div className="development-target" key={t.capability_tag_id}><strong>{tags.find(tag=>tag.id===t.capability_tag_id)?.name||"目标能力"}</strong><label className="enablement-field">本次目标要求<input value={t.requirement} maxLength={1000} onChange={e=>set("targets",form.targets.map((v,j)=>i===j?{...v,requirement:e.target.value}:v))}/></label><label className="development-check"><input type="checkbox" checked={t.confirmed_gap} onChange={e=>set("targets",form.targets.map((v,j)=>i===j?{...v,confirmed_gap:e.target.checked}:v))}/>我明确确认该项存在能力差距</label>{t.confirmed_gap&&<label className="enablement-field">人工确认依据<input value={t.confirmation_note} onChange={e=>set("targets",form.targets.map((v,j)=>i===j?{...v,confirmation_note:e.target.value}:v))}/></label>}<button type="button" className="secondary-btn" onClick={()=>set("targets",form.targets.filter((_,j)=>j!==i))}>移除目标</button></div>)}
 <h3>硬约束</h3><p className="muted">没有限制的项请明确填写“无要求”。未知条件不会按符合处理。</p><div className="development-grid">{constraints.map(key=><label key={key} className="enablement-field">{labels[key]}<input value={form.constraints[key]||""} maxLength={300} placeholder="填写限制或无要求" onChange={e=>set("constraints",{...form.constraints,[key]:e.target.value})}/></label>)}</div>
 <label className="development-check"><input type="checkbox" checked={form.model_input_allowed} onChange={e=>set("model_input_allowed",e.target.checked)}/>允许将填写的发展目标、人员基础、约束和调整指令发送至能力发展场景模型；原始诉求、伙伴内部画像和附件不发送</label>
 <label className="development-check"><input type="checkbox" checked={form.partner_goal_allowed} onChange={e=>set("partner_goal_allowed",e.target.checked)}/>允许在伙伴可传递视图中展示本次发展目标</label>
 {missing.length>0&&<div className="notice-neutral" data-testid="clarification"><h3>提交前澄清</h3><p>请补全：{missing.map(k=>labels[k]||k).join("、")}。尚未创建生成任务。</p><label className="development-check"><input type="checkbox" checked={assume} onChange={e=>{setAssume(e.target.checked);if(!e.target.checked)set("accepted_assumptions",{});}}/>按明确填写的假设继续</label>{assume&&missing.filter(k=>!["target_partner_id","raw_demand","targets","model_input_allowed","confirmation_note"].includes(k)).map(key=><label key={key} className="enablement-field">接受的假设：{labels[key]}<input value={form.accepted_assumptions[key]||""} onChange={e=>set("accepted_assumptions",{...form.accepted_assumptions,[key]:e.target.value})}/></label>)}</div>}
 {Object.keys(form.accepted_assumptions).length>0&&<p>已接受假设：{Object.entries(form.accepted_assumptions).map(([k,v])=>`${labels[k]}：${v}`).join("；")}</p>}
 {error&&<p className="notice-neutral" role="alert">{error}</p>}<button type="button" disabled={busy} onClick={()=>void submit()}>{busy?"正在提交…":initial?"提交调整并生成新草稿":"生成发展方案"}</button>
 </section>;
}

function cleanStages(stages:Stage[]):Stage[]{return stages.map(s=>({title:s.title,items:s.items.map(i=>({source_type:i.source_type,source_id:i.source_id,source_version:i.source_version,capability_tag_id:i.capability_tag_id,reason:i.reason,estimated_hours:i.estimated_hours,note:i.note}))}));}
export function DevelopmentPlanDetail({id}:{id:string}){
 const [data,setData]=useState<Detail|null>(null),[error,setError]=useState(""),[selected,setSelected]=useState(""),[editing,setEditing]=useState<Stage[]|null>(null),[editBase,setEditBase]=useState(""),[options,setOptions]=useState<Candidate[]>([]),[revision,setRevision]=useState(false),[revisionBase,setRevisionBase]=useState<string|null>(null),[instruction,setInstruction]=useState(""),[preview,setPreview]=useState(""),[previewVersion,setPreviewVersion]=useState(""),[busy,setBusy]=useState(false),[corrections,setCorrections]=useState<Record<string,string>>({}),[names,setNames]=useState<Record<string,string>>({});
 const loadSequence=useRef(0);
 async function load(){const seq=++loadSequence.current;try{const next=await request<Detail>(`/development/plans/${id}${selected?`?version_id=${encodeURIComponent(selected)}`:""}`);if(seq===loadSequence.current)setData(next);}catch(e){if(seq===loadSequence.current){setData(null);setPreview("");setError((e as Error).message);}}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),2000);return()=>{clearInterval(timer);loadSequence.current++;};},[id,selected]); // Reauthorize every read; previews are never used for copying.
 useEffect(()=>{request<{id:string;name:string}[]>("/development/capabilities").then(tags=>setNames(Object.fromEntries(tags.map(t=>[t.id,t.name])))).catch(()=>{});},[]);
 useEffect(()=>{setPreview("");setPreviewVersion("");},[data?.hidden,data?.plan.confirmed_version_id]);
 useEffect(()=>{if(!previewVersion)return;let active=true;const refresh=async()=>{try{const result=await request<{text:string}>(`/development/plans/${id}/transferable`);if(active)setPreview(result.text);}catch(e){if(active){setPreview("");setPreviewVersion("");setError((e as Error).message);}}};const timer=setInterval(()=>void refresh(),15000);window.addEventListener("focus",refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener("focus",refresh);};},[id,previewVersion]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn();await load();tasksChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!data)return <div className="page"><p role="status">{error||"正在读取发展方案…"}</p></div>;
 const {plan,payload}=data;const versionName=(v:string|null)=>v?`V${data.versions.find(x=>x.id===v)?.version_no||"?"}`:"未确认";const running=!!plan.active_run_id;const locked=busy||running||plan.status==="archived";const historical=!!selected&&selected!==plan.current_version_id;
 return <div className="page development-detail"><Link href="/tasks">← 全部任务</Link><div className="page-heading-row"><div><p className="eyebrow">Development Plan</p><h1>{data.partner_name} · 能力发展方案</h1><p>当前版本：<strong>{plan.current_version_id?versionName(plan.current_version_id)+(plan.current_version_id===plan.confirmed_version_id?"（已确认）":"（草稿）"):"尚未生成"}</strong> · 已确认版本：<strong>{versionName(plan.confirmed_version_id)}</strong></p><PlanStatus value={data.presentation}/></div></div>
 {error&&<div role="alert" className="notice-neutral">{error}</div>}{running&&<div className="notice-neutral" role="status">发展方案生成中 · 每次运行独立保存，旧版本仍保留。</div>}{data.runs[0]?.safe_error_message&&<div className="notice-neutral">{data.runs[0].safe_error_message}</div>}{data.notice&&<div className="notice-neutral">{data.notice}</div>}
 <div className="enablement-actions"><button disabled={locked||!plan.current_version_id||historical||data.hidden} onClick={()=>void action(async()=>{await request(`/development/plans/${id}/confirm`,{version_id:plan.current_version_id});})}>确认当前版本</button><button className="secondary-btn" disabled={locked||data.hidden} onClick={()=>{setRevisionBase(plan.current_version_id);setRevision(v=>!v);}}>对话调整</button><button className="secondary-btn" disabled={locked||!payload||historical} onClick={()=>void action(async()=>{setOptions(await request<Candidate[]>(`/development/plans/${id}/candidates`));setEditing(cleanStages(payload!.stages));setEditBase(plan.current_version_id!);setCorrections({});})}>结构化编辑</button><button className="secondary-btn" disabled={busy||running} onClick={()=>void action(async()=>{await request(`/agent/tasks/${id}/${plan.status==="archived"?"restore":"archive"}`,{},"PATCH");})}>{plan.status==="archived"?"恢复方案":"归档方案"}</button><button className="secondary-btn" disabled={busy||!plan.confirmed_version_id||data.hidden||plan.status==="archived"} onClick={()=>void action(async()=>{const result=await request<{text:string}>(`/development/plans/${id}/transferable`);setPreview(result.text);setPreviewVersion(plan.confirmed_version_id!);})}>伙伴可传递视图预览</button></div>
 {preview&&<section className="card" data-testid="transfer-preview"><h2>伙伴可传递视图</h2><p className="muted">仅使用已确认版本，通过现有业务渠道传递。</p><pre className="development-text">{preview}</pre><button disabled={busy} onClick={()=>void action(async()=>{const result=await request<{text:string}>(`/development/plans/${id}/copy`,{version_id:previewVersion});await navigator.clipboard.writeText(result.text);setPreview(result.text);})}>复制内容</button><button className="secondary-btn" onClick={()=>{setPreview("");setPreviewVersion("");}}>关闭预览</button></section>}
 {revision&&!data.hidden&&<section><label className="enablement-field">调整指令<textarea value={instruction} maxLength={2000} onChange={e=>setInstruction(e.target.value)} placeholder="例如缩短周期、改变目标或资源偏好。新草稿将展示调整后的安排，也可在下方明确修改字段。"/></label><DevelopmentRequestForm key={id+"revise"} partnerId={data.request.target_partner_id} sourceTask={data.request.source_task_id} sourceCase={data.request.source_case_id} sourceVersion={data.request.source_case_version} initial={data.request} onSave={async value=>{await request(`/development/plans/${id}/revise`,{submission_id:crypto.randomUUID(),based_on_version_id:revisionBase,instruction,request:value});setRevision(false);setSelected("");await load();tasksChanged();}}/></section>}
 <section className="card"><h2>方案总览</h2>{!data.hidden&&<><h3>{payload?.overview.development_goal||data.request.development_goal}</h3><p>参训对象：{payload?.overview.trainee_role||data.request.trainee_role} · {payload?.overview.trainee_count||data.request.trainee_count} 人</p><p>周期：{payload?.overview.duration_weeks||data.request.duration_weeks} 周 · 每周 {payload?.overview.hours_per_week||data.request.hours_per_week} 小时</p><details><summary>原始诉求及来源</summary><p className="development-text">{data.request.raw_demand}</p><p>诉求来源：{({partner:"伙伴",partner_manager:"伙伴发展经理",jointly_confirmed:"双方共同确认"} as Record<string,string>)[data.request.request_source]}</p>{data.request.source_task_id&&<Link href={`/tasks/${data.request.source_task_id}`}>来源项目（原风险待能力发展流程复核）</Link>}{data.request.source_case_id&&<p>源自共享学习案例版本 {data.request.source_case_version}</p>}</details></>}
 <label className="enablement-field">查看版本<select value={selected} onChange={e=>{setSelected(e.target.value);setEditing(null);}}><option value="">当前版本</option>{data.versions.map(v=><option key={v.id} value={v.id}>V{v.version_no}{v.id===plan.confirmed_version_id?" · 已确认":" · 历史快照"}</option>)}</select></label></section>
 {payload&&<><section className="card" data-testid="diagnoses"><h2>诊断依据</h2><p className="muted">目标满足度与证据状态分别判断；模型推断不构成已确认的业务事实。</p>{payload.diagnoses.map(d=><div className="development-target" key={d.capability_tag_id}><h3>{names[d.capability_tag_id]||"目标能力"} · {d.target_requirement}</h3><div className="development-grid"><p>目标满足度：{labels[d.target_satisfaction]}</p><p>证据状态：{labels[d.evidence_status]}</p><p>判断来源：{labels[d.judgment_source]}</p><p>问题分类：{labels[d.problem_type]}</p></div>{d.confirmation&&<p>确认依据：{d.confirmation.note}</p>}<p>引用依据：{d.evidence_refs.length?"已授权引用":"暂无允许发送模型的目标证据；需业务核实"}</p><p>待核实事项：{d.pending_verifications.join("；")||"无补充事项"}</p></div>)}</section>
 <section className="card" data-testid="stages"><h2>分阶段资源安排</h2>{payload.stages.map((s,index)=><div className="development-target" key={index}><h3>{index+1}. {s.title}</h3>{s.items.length?s.items.map((i,n)=><article className="development-resource" key={n}><h4>{labels[i.source_type]} · {i.title}</h4><p>目标能力：{names[i.capability_tag_id]||"已选目标"}</p><p>{i.reason}</p><p>先修条件：{i.prerequisites||"未知"} · 预计投入 {i.estimated_hours} 小时</p><p>约束判定：{labels[i.constraint?.state||"unknown"]} · {labels[i.availability||"unavailable"]}</p>{i.note&&<p>内部备注：{i.note}</p>}{i.availability==="available"&&<Link href={`/enablement/resources/${i.source_type}/${i.source_id}?source_version=${i.source_version}`}>查看来源与发起跳转</Link>}</article>):<p>该阶段暂无可安排资源，需补充资料或核实资源缺口。</p>}</div>)}</section>
 <section className="card" data-testid="gaps"><h2>限制与资源缺口</h2>{[...payload.limitations,...payload.resource_gaps].map((v,i)=><p key={i}>{v}</p>)}{!payload.limitations.length&&!payload.resource_gaps.length&&<p>当前未记录额外限制，实施前仍需核实访问条件。</p>}{Object.keys(payload.assumptions).length>0&&<><h3>已接受的假设</h3>{Object.entries(payload.assumptions).map(([k,v])=><p key={k}>{labels[k]}：{v}</p>)}</>}</section></>}
 {editing&&<section className="card" data-testid="structured-edit"><h2>结构化编辑</h2><p>保存后创建新草稿；诊断纠正必须记录新的业务确认依据。</p>{editing.map((s,si)=><div key={si} className="development-target"><label className="enablement-field">阶段标题<input value={s.title} onChange={e=>setEditing(editing.map((v,j)=>j===si?{...v,title:e.target.value}:v))}/></label><button className="secondary-btn" disabled={si===0} onClick={()=>{const next=[...editing];[next[si-1],next[si]]=[next[si],next[si-1]];setEditing(next);}}>阶段上移</button>{s.items.map((i,ii)=><div className="development-resource" key={ii}><p>{options.find(o=>o.source_id===i.source_id)?.title||"历史资源"}</p><label className="enablement-field">预计投入<input type="number" min="0.5" value={i.estimated_hours} onChange={e=>setEditing(editing.map((v,j)=>j===si?{...v,items:v.items.map((x,k)=>k===ii?{...x,estimated_hours:Number(e.target.value)}:x)}:v))}/></label><label className="enablement-field">内部备注<input value={i.note} onChange={e=>setEditing(editing.map((v,j)=>j===si?{...v,items:v.items.map((x,k)=>k===ii?{...x,note:e.target.value}:x)}:v))}/></label><button className="secondary-btn" onClick={()=>setEditing(editing.map((v,j)=>j===si?{...v,items:v.items.filter((_,k)=>k!==ii)}:v))}>移除资源</button></div>)}<select aria-label={`阶段 ${si+1} 添加资源`} value="" onChange={e=>{const c=options[Number(e.target.value)];if(!c)return;const cap=c.capability_tag_ids.find(t=>payload?.diagnoses.some(d=>d.capability_tag_id===t&&d.problem_type==="trainable_gap"));if(!cap)return;setEditing(editing.map((v,j)=>j===si?{...v,items:[...v.items,{source_type:c.source_type,source_id:c.source_id,source_version:c.source_version,capability_tag_id:cap,reason:"用户选择的资源",estimated_hours:1,note:""}]}:v));}}><option value="">添加 / 替换资源（先移除旧项）</option>{options.map((o,i)=><option key={i} value={i}>{o.title}</option>)}</select></div>)}<button className="secondary-btn" onClick={()=>setEditing([...editing,{title:"新阶段",items:[]}])}>添加阶段</button>{payload?.diagnoses.map(d=><label className="enablement-field" key={d.capability_tag_id}>业务纠正：确认“{names[d.capability_tag_id]}”存在可培养差距的依据（可选）<input value={corrections[d.capability_tag_id]||""} onChange={e=>setCorrections({...corrections,[d.capability_tag_id]:e.target.value})}/></label>)}<div className="enablement-actions"><button disabled={busy} onClick={()=>void action(async()=>{await request(`/development/plans/${id}/edit`,{based_on_version_id:editBase,stages:cleanStages(editing),corrections:Object.fromEntries(Object.entries(corrections).filter(([,v])=>v.trim()))});setEditing(null);setSelected("");})}>保存新草稿</button><button className="secondary-btn" onClick={()=>setEditing(null)}>取消编辑</button></div></section>}
 <section className="card"><h2>运行历史</h2>{data.runs.map((r,i)=><p key={r.id}>第 {data.runs.length-i} 次 · {r.run_type==="generate"?"生成":"调整"} · {labels[r.status]||r.status} · {new Date(r.created_at).toLocaleString("zh-CN")}</p>)}</section></div>;
}
