local all banfei_agentarts_admin peer map=agentarts_admin
local all all reject
host banfei_agentarts banfei_agentarts_app 127.0.0.1/32 scram-sha-256
host all all 127.0.0.1/32 reject
host all all ::1/128 reject
