import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';

test('fixed agents save independently and keep existing entry and task ownership',async({page})=>{
 const options={modelConfigId:'model-1',thinking:true,timeoutSeconds:300,timeoutRetries:3};
 const settings={agents:{partner_match:{...options,name:'伙伴匹配',description:'结合需求寻找交付伙伴。',icon:'users',enabled:true,executor:'local',runtimeUrl:null as string|null},partner_development:{...options,name:'伙伴发展',description:'提供发展建议与资源。',icon:'trend',enabled:true,executor:'local',runtimeUrl:null as string|null}},processing:{...options}};
 const developmentBefore=JSON.stringify(settings.agents.partner_development),unexpected:string[]=[],errors:string[]=[];
 const admin={id:'synthetic-admin',username:'synthetic-admin',role:'admin',status:'active',must_change_password:false};
 const user={id:'synthetic-user',username:'synthetic-user',role:'user',status:'active',must_change_password:false};
 await page.addInitScript(({admin,user})=>{for(const [scope,value] of [['admin',admin],['user',user]] as const){localStorage.setItem(`banfei:${scope}:token`,'synthetic-ui-only');localStorage.setItem(`banfei:${scope}:user`,JSON.stringify(value));}}, {admin,user});
 page.on('pageerror',error=>errors.push(error.message));
 const stamp=new Date().toISOString();
 const task={id:'history-match',requirement:'既有合成任务的原始需求',createdAt:stamp,createdBy:'合成用户',taskStatus:'ready',task_type:'partner_match',archivedAt:null};
 await page.route('**/api/**',async route=>{
  const request=route.request(),path=new URL(request.url()).pathname.replace(/^\/api/,'');
  if(path==='/auth/me')return route.fulfill({json:request.headers().authorization?.includes('synthetic')&&(await page.url()).includes('/admin')?admin:user});
  if(path==='/admin/model-configs')return route.fulfill({json:[1,2].map(i=>({id:`model-${i}`,name:i===1?'DeepSeek 主连接':'DeepSeek 备用连接',modelName:'deepseek-flash',baseUrl:'https://api.deepseek.com',provider:'OpenAI Compatible',enabled:true,apiKeyConfigured:true,maxTokens:384000,temperature:.3,isDefault:false}))});
  if(path==='/admin/agents')return route.fulfill({json:settings});
  if(path==='/admin/agents/partner_match'&&request.method()==='PUT'){settings.agents.partner_match=request.postDataJSON();return route.fulfill({json:settings});}
  if(path==='/agents')return route.fulfill({json:Object.entries(settings.agents).map(([id,a])=>({id,name:a.name,description:a.description,icon:a.icon,enabled:a.enabled}))});
  if(path==='/agent/tasks')return route.fulfill({json:{items:[task],total:1,page:1,pageSize:10,totalPages:1}});
  if(path==='/agent/tasks/history-match')return route.fulfill({json:{...task,recommendations:[],answer:'已保存的合成匹配结果仍可查看。',demandProfile:null,opportunity:null}});
  if(path==='/partners')return route.fulfill({json:[]});
  if(path==='/enablement/context')return route.fulfill({json:{partner:null,project:null,shared_case:null,evidence:[]}});
  if(path==='/health')return route.fulfill({json:{status:'ok'}});
  unexpected.push(request.method()+' '+path);return route.fulfill({status:404,json:{detail:'Unspecified synthetic route'}});
 });
 await page.goto('/admin/models');
 await expect(page.getByRole('heading',{name:'智能体管理',exact:true})).toBeVisible();
 const matching=page.getByTestId('agent-partner_match');
 await expect(page.getByTestId('agent-partner_development')).toBeVisible();
 await expect(page.getByText('业务场景模型配置',{exact:true})).toHaveCount(0);
 await matching.getByLabel('展示名称').fill('项目伙伴顾问');
 await matching.getByLabel('简介').fill('根据项目需求核实伙伴经验与交付边界。');
 await matching.getByLabel(/^图标/).selectOption('puzzle');
 await matching.getByLabel(/^模型/).selectOption('model-2');
 await matching.getByLabel('执行位置').selectOption('runtime');
 await matching.getByLabel('该智能体的 Runtime 地址').fill('https://synthetic.huaweicloud-agentarts.com/runtimes/match/invocations');
 await matching.getByLabel('请求超时（秒）').fill('180');
 await matching.getByLabel('开启思考（模型支持时）').uncheck();
 await matching.getByLabel('启用智能体').uncheck();
 await matching.getByRole('button',{name:'保存配置'}).click();
 await expect(matching.getByRole('status')).toHaveText('已保存');
 await page.reload();
 await expect(matching.getByLabel('展示名称')).toHaveValue('项目伙伴顾问');
 await expect(matching.getByLabel('执行位置')).toHaveValue('runtime');
 await expect(matching.getByLabel('该智能体的 Runtime 地址')).toHaveValue('https://synthetic.huaweicloud-agentarts.com/runtimes/match/invocations');
 await expect(page.getByTestId('agent-processing').getByLabel('执行位置')).toHaveCount(0);
 await expect(matching.getByLabel('启用智能体')).not.toBeChecked();
 expect(JSON.stringify(settings.agents.partner_development)).toBe(developmentBefore);
 const evidence=process.env.AGENT_EVIDENCE_DIR;if(evidence)mkdirSync(evidence,{recursive:true});
 if(evidence)await page.screenshot({path:`${evidence}/admin-agents.png`,fullPage:true});
 await page.goto('/');
 await expect(page.getByRole('tab',{name:'项目伙伴顾问',exact:true})).toBeVisible();
 await expect(page.locator('.home-scene-buttons button')).toHaveCount(6);
 await page.locator('#requirement').fill('合成项目需求');
 await expect(page.locator('#match-panel').getByRole('button',{name:'开始',exact:true})).toBeDisabled();
 await expect(page.getByText('该智能体已停用，历史任务仍可查看。',{exact:true})).toBeVisible();
 if(evidence)await page.screenshot({path:`${evidence}/disabled-match-entry.png`,fullPage:true});
 await page.getByRole('tab',{name:'伙伴发展',exact:true}).click();
 await page.getByRole('textbox',{name:'发展方向',exact:true}).fill('合成发展需求');
 await expect(page.locator('#development-panel').getByRole('button',{name:'开始',exact:true})).toBeEnabled();
 if(evidence)await page.screenshot({path:`${evidence}/development-entry.png`,fullPage:true});
 await page.goto('/tasks/history-match');
 await expect(page.locator('[data-agent-id="partner_match"]')).toContainText('项目伙伴顾问');
 await expect(page.getByText('已保存的合成匹配结果仍可查看。',{exact:true})).toBeVisible();
 if(evidence)await page.screenshot({path:`${evidence}/history-agent.png`,fullPage:true});
 expect(unexpected).toEqual([]);expect(errors).toEqual([]);
});
