import {test,expect} from '@playwright/test';
import path from 'node:path';
const API='http://127.0.0.1:8100';
for(const width of [1366,1920])test(`Phase D explicit assumption is accepted and visible in saved version ${width}`,async({page,request})=>{
  const session=await (await request.post(API+'/auth/login',{data:{username:'user_a',password:'ValidationPass123'}})).json();
  const headers={Authorization:`Bearer ${session.access_token}`};
  await page.addInitScript(s=>{localStorage.setItem('token',s.access_token);localStorage.setItem('user',JSON.stringify(s.user));},session);
  await page.setViewportSize({width,height:width===1366?768:1080});
  const before=(await (await request.get(API+'/agent/tasks?task_type=development_plan',{headers})).json()).total;
  const tags=await (await request.get(API+'/development/capabilities',{headers})).json();
  await page.goto('/enablement?partner_id=partner-1');
  for(const [label,value] of [['原始诉求','合成假设路径验证'],['发展目标','数据库迁移'],['参训岗位','交付工程师'],['参训人数','3'],['周期（周）','4'],['每周投入（小时）','3']])await page.getByLabel(label,{exact:true}).fill(value);
  await page.getByLabel('添加目标能力').selectOption(tags.find((t:{name:string})=>t.name==='数据库').id);
  await page.getByLabel('本次目标要求',{exact:true}).fill('能够独立完成迁移验证');
  for(const label of ['语言','站点','账号条件','网络条件','实验环境','费用要求','预算'])await page.getByLabel(label,{exact:true}).fill('无要求');
  await page.getByLabel('允许将填写的发展目标',{exact:false}).check();
  await page.getByRole('button',{name:'生成发展方案',exact:true}).click();
  await expect(page.getByTestId('clarification')).toContainText('人员已知基础');
  expect((await (await request.get(API+'/agent/tasks?task_type=development_plan',{headers})).json()).total).toBe(before);
  await page.getByLabel('按明确填写的假设继续').check();
  const assumption='假设入门，实施前由业务负责人确认';
  await page.getByLabel('接受的假设：人员已知基础',{exact:true}).fill(assumption);
  await expect(page.getByText('已接受假设：',{exact:false})).toContainText(assumption);
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.addStyleTag({content:'nextjs-portal {display:none}'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.screenshot({path:path.resolve(`../artifacts/enablement-phase-d/16-assumption-accepted-${width}.png`),fullPage:true});
  const accepted=page.waitForResponse(r=>r.url()===API+'/development/plans'&&r.request().method()==='POST');
  await page.getByRole('button',{name:'生成发展方案',exact:true}).click();const id=(await (await accepted).json()).plan_id;
  await expect(page).toHaveURL(`/tasks/${id}`);await expect(page.getByTestId('gaps')).toContainText(assumption);
  await page.reload();await expect(page.getByTestId('gaps')).toContainText('已接受的假设');
  await expect(page.getByTestId('gaps')).toContainText(assumption);
  const detail=await (await request.get(API+'/development/plans/'+id,{headers})).json();
  expect(detail.payload.assumptions.known_baseline).toBe(assumption);expect(detail.runs[0].status).toBe('ready');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.addStyleTag({content:'nextjs-portal {display:none}'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.screenshot({path:path.resolve(`../artifacts/enablement-phase-d/17-assumption-persisted-${width}.png`),fullPage:true});
});
